name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: patelprashantdds
          password: ${{ secrets.DOCKER_TOKEN }}
    -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: patelprashantdds/getting-started:latest
          cache-from: type=registry,ref=patelprashantdds/getting-started:buildcache
          cache-to: type=registry,ref=patelprashantdds/getting-started:buildcache,mode=max
